IF EXISTS (SELECT * FROM SYS.FOREIGN_KEYS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[FK_NAME]') AND PARENT_OBJECT_ID = OBJECT_ID(N'[DBO].[MYTABLE]')) 
  ALTER TABLE [DBO].[MYTABLE] DROP CONSTRAINT [FK_NAME] 
GO 

