ALTER TABLE [DBO].[MYTABLE] NOCHECK CONSTRAINT ALL
ALTER TABLE [DBO].[MYTABLE] WITH CHECK CHECK CONSTRAINT ALL
ALTER TABLE [DBO].[MYTABLE] NOCHECK CONSTRAINT CONSTRAINT_NAME
ALTER TABLE [DBO].[MYTABLE] CHECK CONSTRAINT CONSTRAINT_NAME

