DECLARE @STARTTIME TIME, @ENDTIME TIME;
SET @STARTTIME = '10:40';
SET @ENDTIME = '12:30';

;
WITH N(N) AS (SELECT 1 UNION ALL SELECT N+1 FROM N WHERE N < 50)
SELECT @STARTTIME AS T
UNION ALL
SELECT
	CAST(DATEADD(MINUTE,10*N+DATEDIFF(MINUTE,0,@STARTTIME)/10*10,0) AS TIME)
FROM
	N
WHERE
	CAST(DATEADD(MINUTE,10*N+DATEDIFF(MINUTE,0,@STARTTIME)/10*10,0) AS TIME) <= @ENDTIME;
