SELECT  
  MTBL.ID,
  MTBL.STATUS,
  MAX(CASE MVAL.CODE WHEN 'A' THEN MVAL.[VALUE] ELSE NULL END) AS VALUEA,
  MAX(CASE MVAL.CODE WHEN 'B' THEN MVAL.[VALUE] ELSE NULL END) AS VALUEB,
  MAX(CASE MVAL.CODE WHEN 'C' THEN MVAL.[VALUE] ELSE NULL END) AS VALUEC,
  MAX(CASE MVAL.CODE WHEN 'D' THEN MVAL.[VALUE] ELSE NULL END) AS VALUED,
  MAX(CASE MVAL.CODE WHEN 'E' THEN MVAL.[VALUE] ELSE NULL END) AS VALUEE,
  MAX(CASE MVAL.CODE WHEN 'F' THEN MVAL.[VALUE] ELSE NULL END) AS VALUEF,
  MAX(CASE MVAL.CODE WHEN 'G' THEN MVAL.[VALUE] ELSE NULL END) AS VALUEG,
  MAX(CASE MVAL.CODE WHEN 'H' THEN MVAL.[VALUE] ELSE NULL END) AS VALUEH
FROM MYTABLE AS MTBL
     INNER JOIN MYVALUES AS MVAL ON MTBL.ID = MVAL.ID_MYTABLE
GROUP BY 
  MTBL.ID,
  MTBL.STATUS